### ISSUE TITLE
Napaka: could not find function "ddply"

### ISSUE THREAD

**Issue by matijapretnar** [tinarazic/pikado#2]
Ko poženem datoteko `pikado.R` dobim napako

    could not find function "ddply"

zaradi česar tudi spremenljivke `zacetnik`, ..., ki jih potrebuje Shiny, niso definirane. Ali gre za zatipk ali v `libraries.R` manjka še kakšna knjižnica?

**Comment by tinarazic** [comment]
Imate prav. Na gitu je bila še stara verzija, kjer je manjkala knjižnica plyr. Sedaj je popravljeno. Za zagon je potrebno pognati samo datoteko pikado.r

**Comment by matijapretnar** [comment]
Jup, zdaj to dela. Je pa sigurno en zatipk in sicer `funckije`

**Comment by tinarazic** [comment]
Še dobro, da sem se dvakrat zmotila. :) Popravim.
