### ISSUE TITLE
Preveliki podatki

### ISSUE THREAD

**Issue by tinarazic** [tinarazic/pikado#3]
Imam težavo z implementacijo strategije 2 pri igri pikada 301 (glej datoteko `teorija\matematicno_ozadje.pdf`) zaradi prevelikih podatkov in njihove časovne zahtevnosti.

**Kako imam sedaj zastavljeno idejo:** 
Imam prehodno matriko stanj velikosti 40.000 x 40.000. To prehodno matriko stanj bi morala izračunati za različne točke na tabli pikada (trenutno sem definirala 1560 točk, torej 1560 matrik) in potem te matrike uporabiti pri izračunu vrednosti v iterativnem algoritmu(za vsako stanje ena vrednost). Dobila bi optimalno ciljno točko, če sem v določenem stanju pri dani varianci puščice.  Pa recimo, da bi izračunala vse skupaj samo za 3 različne variance (3 različni nivoji igralca). 

**Problem:**
Težava se pojavi že pri izračunu ene prehodne matrike (funkcija `prehodna.matrika.tocka` v datoteki `program/strategija2.r`). Če očistim pomnilnik in zaženem, mi v 10 urah ne naredi matrike.  Verjetno se da moje funkcije kako pohitriti in tudi poenostaviti igro npr: 
- zmanjšati število stanj (gledam izmišljeno igro 101, namesto 301)
- zmanjšati število možnih ciljnih točk ( iz 1560 na minimalno 360)
- velika toleranca pri iterativnem algoritmu.

Vendar mislim, da bi še vedno imela velike matrike in težavo, ker moram naprej z njimi računati.

Razmišljala sem mogoče tudi o tem, da bi implementirala strategijo 2 v pythonu in v R samo vpeljala datoteko optimalnih ciljnih točk za določeno stanje glede na varianco, ter to uporabila v shiny aplikaciji. 

Vesela bi bila mnenja ali kakšnega predloga. @matijapretnar @jO-Osko

**Comment by tinarazic** [comment]
Upam, da je razumljivo napisano. Lahko pa se pogovorimo na govorilnih urah preko zooma.

**Comment by matijapretnar** [comment]
Ja, je razumljivo napisano, ampak imam še vedno nekaj vprašanj, ki bi jih bilo najbolje razrešiti v živo. Ali se slišiva npr. jutri ob 11h?

**Comment by tinarazic** [comment]
Lahko ja...

**Comment by tinarazic** [comment]
Kakšen je id meetinga?

**Comment by matijapretnar** [comment]
Sem poslal na mail.
