### ISSUE TITLE
Zaključek projekta

### ISSUE THREAD

**Issue by tinarazic** [tinarazic/pikado#4]
Pozdravljeni, 

uspešno sem implementirala strategijo 2 in jo vključila v shiny aplikacijo. Upoštevala sem tudi vse komentarje iz kratke predstavitve in govorilnih ur in dodelala svojo aplikacijo.

Imate morda še kakšno pripombo ali nasvet za uspešen zaključek projekta? Lahko imam tudi še eno predstavitev preko zooma.

@matijapretnar

Hvala in lep pozdrav!

**Comment by matijapretnar** [comment]
Ni več potrebno, vse lepo dela. Sem kar vpisal oceno v VIS.
